name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build and Test with Maven
      run: mvn clean install

    # Upload test reports as artifacts
    - name: Upload test results
      if: always() # Always run this step even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: Test-Report
        path: target/surefire-reports # This path should match where Surefire generates reports
