name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and run tests with Maven
        run: mvn clean test

      - name: Generate Surefire Test Report
        run: mvn surefire-report:report

      - name: Check Surefire Report Directory
        run: ls -R target/surefire-reports || echo "Surefire report not found."

      - name: Upload Surefire Test Report
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: target/surefire-reports/index.html  # Adjust path to ensure correct report is uploaded

      # Ensure errors are visible in logs
      - name: Print Test Results
        if: failure()
        run: cat target/surefire-reports/*.txt || echo "No test results found"

