name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and run tests with Maven
        run: mvn clean test

      # Generate and upload the Surefire report
      - name: Generate Surefire Test Report
        run: mvn surefire-report:report

      - name: Upload Surefire Test Report
        uses: actions/upload-artifact@v2
        with:
          name: surefire-report
          path: target/surefire-reports/index.html

      # This will ensure that failed test errors are printed to the CI logs
      - name: Print Test Results
        if: failure()
        run: cat target/surefire-reports/*.txt || echo "No test results found"
